/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Fear Effect 2: Retro Helix)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8005C130u
#define func_8005C130 BootEntry  /* alias */
